project:
  type: website

website:
  title: "Pregnancy Data"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Sources
      - about.qmd
      
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true