project:
  type: website

website:
  title: "Pregnancy Data"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: sources.qumd
        text: Sources
      - href: about.qmd
        text: About
      
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true